appURL=http://192.168.1.81/opencart/upload/index.php
email=azeez12333@gmail.com
password=Aa@849984
#execution_env=local
execution_env=remote
hub_url=http://192.168.1.81:4444
grid_type=docker
#grid_type=non_docker